apiVersion: v1
kind: Service
metadata:
  name: multi-cloud-service
spec:
  selector:
    app: multi-cloud
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 31000
  type: LoadBalancer
